name: Github Action flow to Docker hub for Fib

on:
    push:
        branches: [master]
        tags: 'v*'
		
		
jobs:
    build-push-images:
        name: Budowa i publikacja obrazu fib na rezpozytorium
        runs-on: ubuntu-20.04
		
    steps:
	
        - name: Checkout code
          uses: actions/checkout@v2
		
        - name: Buildx set-up
          id: buildx
          uses: docker/setup-buildx-action@v1
		  
        - name: Docker Setup QEMU
          uses: docker/setup-qemu-action@v2
		  
        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{secrets.DOCKER_HUB_USERNAME}}
            password: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
        - name: GitHub login
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.PASS }}
            
        - name: Docker meta
          id: meta
          uses: docker/metadata-action@v4
          with:
            images: |
                Borokoro/chmury-1
                ghcr.io/${{ github.repository }}
            tags: |
                type=ref,event=branch
                type=ref,event=pr
                type=semver,pattern={{version}}
                type=semver,pattern={{major}}.{{minor}}
            
            
        - name: Build and push
          id: docker_build
          uses: docker/build-push-action@v2
          with:
            cache-from: type=registry,ref=docker.io/borokoro6/fib:cache
            cache-to: type=registry,ref=docker.io/borokoro6/fib:cache,mode=max
            platforms: linux/arm/v7,linux/arm64/v8,linux/amd64 
            labels: ${{ steps.meta.outputs.labels }}
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ steps.meta.outputs.tags }}
                
                
            
